### ISSUE TITLE
How do you set up dummyserver on an iPhone

### ISSUE THREAD

**Issue by MikeFarrow** [dai-shi/codeonmobile#1]
Love the app and this is not a bug but how do I get dummyserver to run?

**Comment by dai-shi** [comment]
Thanks for your interest.
The dummySever will just run if you have the proper file in the repo. Please refer the one in this repo. The issue is actually there is not an easy way to debug the dummyServer. 

Hope this helps and more questions are welcomed.

**Comment by MikeFarrow** [comment]
Thanks for the speedy answer, is there anything I need to configure? I am getting a:

'no such file' message

**Comment by dai-shi** [comment]
There is no configuration, just the file name "dummyServer.js".
Is it possible for me to see the file? Is it in a public repository?

**Comment by MikeFarrow** [comment]
https://github.com/MikeFarrow/tst

It is just a test repository

**Comment by dai-shi** [comment]
Just a quick guess. If you are using my dummySever code, try putting index.html into "public" directory.

**Comment by MikeFarrow** [comment]
Still seem to be getting the same problem

**Comment by dai-shi** [comment]
Change the line 57 in dummyServer.js to

```
req.url = '/static/index.html';
```

This should help.

**Comment by MikeFarrow** [comment]
Brilliant dai-shi, that solved the problem
